language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database migrate; create user pg superuser;' -U postgres

notifications:
  email: false

env:
  global:
    - DBMIGRATE_URL=postgres://pg@localhost:5432/migrate
    - DBMIGRATE_PATH=migrations/
