language: rust
rust:
  - stable
  - beta
  - nightly

sudo: false

notifications:
  email: false

addons:
  postgresql: "9.4.1"

services:
  - postgresql

before_script:
  - psql -c 'create database migrate; create user pg superuser;' -U postgres

env:
  - DBMIGRATE_URL=postgres://pg@localhost:5432/migrate DBMIGRATE_PATH=migrations/
