language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - DBMIGRATE_URL=postgres://postgres@localhost/migrate
    - DBMIGRATE_PATH=migrations/
notifications:
  email: false
