[package]
name = "dbmigrate"
version = "0.1.2"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "CLI tool to create and run SQL migrations. Postgres only for now."
homepage = "https://github.com/Keats/dbmigrate"
repository = "https://github.com/Keats/dbmigrate"
keywords = ["database", "postgres", "migration", "sql"]

[dependencies]
regex = "0.1"
url = "0.5"
clap = "1.5.2"
postgres = "0.11"
mysql = "1.2"
clippy = {version = "0.0.31", optional = true}
time = "0.1"
term = "0.2"

[dev-dependencies]
tempdir = "0.3.4"

[features]
default = []
dev = ["clippy"]
